ALTER TABLE articles ADD COLUMN IF NOT EXISTS seo_title VARCHAR(500);
ALTER TABLE articles ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE articles ADD COLUMN IF NOT EXISTS focus_keyword VARCHAR(255);
